type Query {
  ola: String!
  teste: String!
  horaCerta: String!
  horaDate: Date!
  usuarioLogado: User
  produtoEmDestaque: Produto
  numerosMegaSena: [Int!]!
  usuarios: [User]
  usuario(id: Int): User
  usuarioDes(id: Int): User
  perfis: [Perfil]
  perfil(id: Int): Perfil
}
