type User {
  id: Int
  nome: String!
  email: String!
  idade: Int
  salario: Float
  vip: Boolean
  perfil: Perfil
  status: UserStatus
}

enum UserStatus {
  ATIVO
  INATIVO
  BLOQUEADO
}

type Perfil {
  id: Int
  nome: String!
}

input  UserInput {
  nome: String
  email: String
  idade: Int
}

input UserFilter {
  id: Int
  email: String
}